main:
  push:
    - stageOne:
      runner:
        cpus: 8
      services:
        - docker
        - git-clone-yyds
      stages:
        - name: sync to github
          image: tencentcom/git-sync
          imports: https://cnb.cool/eryajf/build-env/-/blob/main/env.yaml
          settings:
            branch: main
            auth_type: https
            username: ${GIT_USERNAME}
            password: ${GIT_ACCESS_TOKEN}
            target_url: https://github.com/opsre/JenkinsGuide.git
            git_email: 'github-actions[bot]@users.noreply.github.com'
    - stageTwo:
      runner:
        cpus: 16
      services:
        - docker
        - git-clone-yyds
      docker:
        image: docker.cnb.cool/znb/images/node:18
        volumes:
          - /data/.cache:copy-on-write
      stages:
        - name: print node version
          script: |
            node -v && npm -v && yarn -v && pnpm -v
        - name: install dependencies
          script: |
            pnpm install
        - name: build project
          script: |
            pnpm build